/hst:hst/hst:configurations/channelpagesupdemo-fr/hst:sitemap:
  jcr:primaryType: hst:sitemap
  jcr:uuid: 1bfdf318-c53c-49a1-befb-5efcc907ce23
  /root:
    jcr:primaryType: hst:sitemapitem
    jcr:uuid: e60077d9-4f1a-456f-96a9-1b3f9d43788d
    hst:componentconfigurationid: hst:pages/homepage
    hst:refId: root
  /_any_:
    jcr:primaryType: hst:sitemapitem
    jcr:uuid: 4cf563fe-efa0-4878-9b81-b784782d3821
    hst:componentconfigurationid: hst:pages/pagenotfound
  /pagenotfound:
    jcr:primaryType: hst:sitemapitem
    jcr:uuid: 89889954-2164-43b9-ba7d-19f9785867b4
    hst:componentconfigurationid: hst:pages/pagenotfound
    hst:refId: pagenotfound
  /events:
    jcr:primaryType: hst:sitemapitem
    jcr:uuid: a3bbda1e-4e60-4427-8f5e-15694e0eec90
    hst:componentconfigurationid: hst:pages/eventslist
    hst:relativecontentpath: events
    /_any_.html:
      jcr:primaryType: hst:sitemapitem
      jcr:uuid: 721d84e5-d24f-46f4-930b-e0674353c035
      hst:componentconfigurationid: hst:pages/eventspage
      hst:relativecontentpath: ${parent}/${1}
    /_any_:
      jcr:primaryType: hst:sitemapitem
      jcr:uuid: 77c5f80b-3de7-480d-8dc4-eb7678d02dad
      hst:componentconfigurationid: hst:pages/eventslist
      hst:relativecontentpath: ${parent}/${1}
  /news:
    jcr:primaryType: hst:sitemapitem
    jcr:uuid: 2895b914-ccda-4e0d-98ec-5b4361ec3318
    hst:componentconfigurationid: hst:pages/newslist
    hst:relativecontentpath: news
    /_any_.html:
      jcr:primaryType: hst:sitemapitem
      jcr:uuid: 96016a58-1413-4974-b305-e762f11dafe4
      hst:componentconfigurationid: hst:pages/newspage
      hst:relativecontentpath: ${parent}/${1}
    /_any_:
      jcr:primaryType: hst:sitemapitem
      jcr:uuid: 73a3a391-0ac4-4e82-9200-0fca025414f0
      hst:componentconfigurationid: hst:pages/newslist
      hst:relativecontentpath: ${parent}/${1}
  /content:
    jcr:primaryType: hst:sitemapitem
    jcr:uuid: cfe31e70-4c9d-411f-8990-0f80c0c2f635
    hst:componentconfigurationid: hst:pages/contentlist
    hst:relativecontentpath: content
    /_any_.html:
      jcr:primaryType: hst:sitemapitem
      jcr:uuid: d8e64d9d-0563-400f-86fc-06844cefe6f9
      hst:componentconfigurationid: hst:pages/contentpage
      hst:relativecontentpath: ${parent}/${1}
    /_any_:
      jcr:primaryType: hst:sitemapitem
      jcr:uuid: d61dcd7a-4386-4f4d-87e5-5dfa17f0e359
      hst:componentconfigurationid: hst:pages/contentlist
      hst:relativecontentpath: ${parent}/${1}
