definitions:
  config:
    /hst:hst/hst:configurations/channelpagesupdemo/hst:catalog:
      jcr:primaryType: hst:catalog
      /channelpagesupdemo-catalog:
        jcr:primaryType: hst:containeritempackage
