/hst:hst/hst:configurations/channelpagesupdemo-fr/hst:pages/contentlist:
  jcr:primaryType: hst:component
  jcr:uuid: 483409e8-9e18-4805-919b-b5f37ea9a7fd
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponentreference
    hst:referencecomponent: contentlist/main
