/hst:hst/hst:configurations/channelpagesupdemo-fr/hst:pages/contentpage:
  jcr:primaryType: hst:component
  jcr:uuid: e014a2a7-e0f6-4da1-bbec-13405f68a43e
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponentreference
    hst:referencecomponent: contentpage/main
