/hst:hst/hst:configurations/channelpagesupdemo-fr/hst:pages/newslist:
  jcr:primaryType: hst:component
  jcr:uuid: 7736c0b0-481c-4843-a782-a4423600916e
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponentreference
    hst:referencecomponent: newslist/main
