/hst:hst/hst:configurations/channelpagesupdemo-fr/hst:pages/pagenotfound:
  jcr:primaryType: hst:component
  jcr:uuid: 0074c397-8c02-43d0-bf70-9a281cf0d9e6
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:component
    jcr:uuid: edbf337e-8aa5-4b26-bd6e-8d2c2e69cade
    hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsPageNotFoundComponent
    hst:template: pagenotfound-main
    /container:
      jcr:primaryType: hst:containercomponentreference
      hst:referencecomponent: pagenotfound/main
