/hst:hst/hst:configurations/channelpagesupdemo-fr/hst:prototypepages/contentpage:
  jcr:primaryType: hst:component
  jcr:mixinTypes: ['hst:prototypemeta']
  jcr:uuid: d66e55fd-4d9b-4ac1-b6ac-ffe388be38b2
  hst:displayname: Simple Content Page
  hst:primarycontainer: main
  hst:referencecomponent: hst:abstractpages/base
  /main:
    jcr:primaryType: hst:containercomponent
    jcr:uuid: 7187e19a-15a8-4265-98d8-c7fc0b7838cf
    hst:label: Content Page Main
    hst:xtype: hst.vbox
