definitions:
  config:
    /hippo:namespaces/channelpagesupdemo/eventsdocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: c810ae0d-e5c3-4a04-b465-dd9ea51b8721
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: d41d740b-f51c-4596-b847-6fe3d805d2d0
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: a92ccb56-7c23-489d-a6a5-ac6e80997d62
          hipposysedit:node: true
          hipposysedit:supertype: ['channelpagesupdemo:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/channelpagesupdemo/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /content:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:content
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /date:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:date
            hipposysedit:primary: false
            hipposysedit:type: Date
          /enddate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:enddate
            hipposysedit:primary: false
            hipposysedit:type: Date
          /image:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:image
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /location:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: channelpagesupdemo:location
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: channelpagesupdemo:eventsdocument
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 9ed0540e-9b5b-45d4-b033-9151d534f17a
          channelpagesupdemo:date: 0001-01-01T13:00:00+01:00
          channelpagesupdemo:documenttype: event
          channelpagesupdemo:enddate: 0001-01-01T13:00:00+01:00
          channelpagesupdemo:introduction: ''
          channelpagesupdemo:title: ''
          hippo:related___pathreference: []
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2013-09-16T18:03:51.692+02:00
          hippostdpubwf:lastModificationDate: 2013-09-16T18:03:51.691+02:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /channelpagesupdemo:content:
            jcr:primaryType: hippostd:html
            hippostd:content: <html><body></body></html>
          /channelpagesupdemo:image:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          type: channelpagesupdemo:eventsdocument
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /content:
            jcr:primaryType: frontend:plugin
            field: content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /date:
            jcr:primaryType: frontend:plugin
            field: date
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /enddate:
            jcr:primaryType: frontend:plugin
            field: enddate
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /location:
            jcr:primaryType: frontend:plugin
            field: location
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /image:
            jcr:primaryType: frontend:plugin
            field: image
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
